"""
Demo fixture — returned when DEMO_MODE=1 in .env.
Update with any real pipeline output to keep it realistic.
"""

DEMO_RESULT = {
    "ticker": "AAPL",
    "financial_data": "--- PYTHON PRE-COMPUTED QUANT METRICS (3-YEAR TREND) ---\nOperating Margin: [29.82%, 31.51%, 31.97%] (Oldest to Newest)\nReturn on Equity (ROE): [156.08%, 164.59%, 151.91%] (Oldest to Newest)\nCurrent Ratio: [0.99, 0.87, 0.89] (Oldest to Newest)\nDebt-to-Equity Ratio: [1.79, 1.87, 1.34] (Oldest to Newest)\nShares Outstanding (Current): 14681140000\n---------------------------------------------------------\n\nINCOME STATEMENT:\n                  2025-09-30    2024-09-30\nTotal Revenue     4.161610e+11  3.910350e+11\nGross Profit      1.952010e+11  1.806830e+11\nOperating Income  1.330500e+11  1.232160e+11\nNet Income        1.120100e+11  9.373600e+10\nDiluted EPS       7.46          6.08\n\nBALANCE SHEET:\n                      2025-09-30    2024-09-30\nTotal Assets          3.592410e+11  3.649800e+11\nTotal Debt            9.865700e+10  1.066290e+11\nStockholders Equity   7.373300e+10  5.695000e+10\nCurrent Assets        1.479570e+11  1.529870e+11\nCurrent Liabilities   1.656310e+11  1.763920e+11\n\nCASH FLOW:\n                    2025-09-30    2024-09-30\nOperating Cash Flow 1.114820e+11  1.182540e+11\nFree Cash Flow      9.876700e+10  1.088070e+11\nCapital Expenditure -1.271500e+10 -9.447000e+09",
    "news_headlines": [
        "Apple reports record Q1 revenue of $143.8B, up 16% year over year, driven by iPhone and Services.",
        "Apple Intelligence sees majority adoption among enabled iPhone users within weeks of launch.",
        "Greater China revenue rebounds 38% as iPhone 17 series drives record upgrader and switcher growth.",
    ],
    "mda_text": "Apple Inc. fiscal 2025 demonstrated strong momentum across all geographic segments. Total net sales reached $416.2 billion, a 6% increase versus fiscal 2024. Services revenue grew 14% to $109.2 billion with all-time records in both developed and emerging markets. The company repurchased $89.3 billion of common stock and raised its quarterly dividend to $0.26 per share.",
    "transcript_text": "We are reporting our best-ever quarter with $143.8 billion in revenue, up 16% from a year ago and exceeding our expectations. EPS reached an all-time record of $2.84, growing a robust 19% year over year. iPhone revenue grew 23% with all-time records across every geographic segment. Services set an all-time revenue record as well, up 14% from a year ago.",
    "financial_diagnostic": "STEP 1: DATA EXTRACTION & TRAJECTORY ANALYSIS\nOperating Margin expanded from 29.82% to 31.97% over three years, a 215 basis point improvement. Diluted EPS grew from $6.11 to $7.46, a 22% increase. Free Cash Flow remained robust at $98.8B despite capital return activity.\n\nSTEP 2: DRIVER IDENTIFICATION & MARGIN DECONSTRUCTION\nRevenue growth of 6.4% YoY outpaced operating expense growth of 8.2%, with Services (75.4% gross margin) becoming a larger mix contributor. Share buybacks reduced diluted share count from 16.3B to 14.7B, amplifying EPS growth beyond net income growth.\n\nSTEP 3: FORWARD PROJECTIONS\nEPS trajectory: Improving. FCF trajectory: Flat to slightly compressing as CapEx scales with AI infrastructure investment.\n\nSTEP 4: QUANTITATIVE RISK & CONVICTION\nConviction: Medium-High. Primary risk: D/E ratio at 1.34x with $98.7B total debt. Secondary risk: Greater China revenue down 4% YoY represents a $2.6B headwind if trend continues.",
    "external_sentiment": 0.0,
    "internal_sentiment": -0.54,
    "transcript_sentiment": 0.75,
    "final_report": "STEP 1: SENTIMENT VS. QUANTITATIVE ALIGNMENT\nThe quantitative data shows Operating Margin expanding to 31.97% and Diluted EPS at $7.46, up 22% over three years. The Internal sentiment score of -0.54 reflects cautious SEC filing language around tariff risk and macro uncertainty, while the Transcript score of +0.75 aligns with the strong earnings delivery.\n\nSTEP 2: TRANSCRIPT CONTEXT & MANAGEMENT TONE\nManagement stated: 'We are reporting our best-ever quarter with $143.8 billion in revenue, up 16%.' EPS reached 'an all-time record of $2.84, growing a robust 19% year over year,' signaling high conviction in near-term trajectory.\n\nSTEP 3: RISK VALIDATION\nThe diagnostic flagged $98.7B in total debt and Greater China weakness (-4% YoY). The transcript acknowledged tariff uncertainty but cited supply chain diversification as a mitigant. External sentiment at 0.00 reflects market-neutral positioning.\n\nSTEP 4: FINAL ENTERPRISE FORECAST\nApple's business trajectory remains positive. Operating Margin expansion to 31.97% combined with aggressive buybacks driving EPS from $6.11 to $7.46 over three years demonstrates durable earnings power. With Services gross margin at 75.4% and growing 14% YoY, mix shift continues to favor high-quality recurring revenue. Near-term EPS of $3.20+ appears achievable barring material tariff escalation.",
}
